SET client_encoding TO 'UTF8';
-- modelo
INSERT INTO modelo_barco (marca, modelo)
VALUES
    ('Alfa', 'Alfa 300'),
    ('Altamar', 'Altamar'),
    ('Altamar', 'Altamar 50'),
    ('Altamar', 'Altamar 50 - Fifty'),
    ('Altamar', 'Altamar 50 Fly'),
    ('Alternativa', 'Alternativa 21'),
    ('Alternativa', 'Alternativa 630'),
    ('Alternativa', 'Marlin 22'),
    ('Aluminatec', 'Alumitec 80'),
    ('Angra', 'Angra 30'),
    ('Angra', 'Angra 32 Full'),
    ('Armada', 'Armada 40'),
    ('Armada Yachts', 'Armada 300M Cabrio'),
    ('Armada Yachts', 'Armada 44 HT'),
    ('Armada Yachts', 'Armada 440 fly'),
    ('Artesanal', 'Trainera de madeira'),
    ('Arthemarine', 'Arthemarine 295'),
    ('Atlantis Yachts', 'Atlantis 345'),
    ('Atlantis Yachts', 'Atlantis 40'),
    ('Atlantis Yachts', 'Atlantis 44'),
    ('Atlantis Yachts', 'Atlantis 48'),
    ('Atlantis Yachts', 'Atlantis 50x4'),
    ('Atlantis Yachts', 'Atlantis 54'),
    ('Axtor', 'Axtor 46'),
    ('Azimut Yachts', 'Azimut 38'),
    ('Azimut Yachts', 'Azimut 40'),
    ('Azimut Yachts', 'Azimut 43'),
    ('Azimut Yachts', 'Azimut 47'),
    ('Azimut Yachts', 'Azimut 48'),
    ('Azimut Yachts', 'Azimut 53'),
    ('Azimut Yachts', 'Azimut 56'),
    ('Azimut Yachts', 'Azimut 58'),
    ('Azimut Yachts', 'Azimut 60'),
    ('Azimut Yachts', 'Azimut 64'),
    ('Azimut Yachts', 'Azimut 70'),
    ('Azimut Yachts', 'Azimut 72 S'),
    ('Azimut Yachts', 'Azimut 78'),
    ('Azimut Yachts', 'Azimut 82'),
    ('Azimut Yachts', 'Azimut 88'),
    ('Bahia', 'Saveiro 53'),
    ('Baia', 'Baia Exuma 59'),
    ('Baja Marine', 'Baja 236'),
    ('Bayliner', 'Bayliner 16'),
    ('Bayliner', 'Bayliner 20.5'),
    ('Bayliner', 'Bayliner Discovery 2660'),
    ('Bayliner', 'Bayliner 28'),
    ('Bayliner', 'Bayliner 280'),
    ('Bayliner', 'Bayliner Cierra 29'),
    ('Bayliner', 'Bayliner 310'),
    ('Bayliner', 'Bayliner 310'),
    ('Bayliner', 'Bayliner 33'),
    ('Bayliner', 'Bayliner 33'),
    ('Bayliner', 'Bayliner Cruiser 330'),
    ('Bayliner', 'Bayliner 350'),
    ('Bayliner', 'Bayliner 350'),
    ('Bayliner', 'Bayliner 40'),
    ('Bayliner', 'Bayliner 55'),
    ('Beneteau', 'Beneteau Monte Carlo 32'),
    ('Beneteau', 'Swift Trawler 34'),
    ('Beneteau', 'Flyer Gran turismo 35'),
    ('Beneteau', 'Flyer Gran Turismo 38'),
    ('Beneteau', 'Flyer Gran turismo 40'),
    ('Beneteau', 'Beneteau 44'),
    ('Benetti', 'Benetti 105'),
    ('Blujoi', 'Catun 31 – Streamline'),
    ('Blujoi', 'Trawcat 40'),
    ('BrasBoats', 'Fly Fish 190'),
    ('Brava', 'Brava 335'),
    ('Brava', 'Brava 335'),
    ('Brava', 'Brava 335 HT'),
    ('Broward', 'Broward 112'),
    ('Caprice', 'Caprice 270'),
    ('Caprice', 'Caprice 330 DayCruiser'),
    ('Caprice', 'Caprice 350'),
    ('Caprice', 'Caprice 480'),
    ('Caprice', 'Caprice 50'),
    ('CarbrasMar', 'CarbrasMar 25'),
    ('CarbrasMar', 'CarbrasMar 25 open'),
    ('CarbrasMar', 'UB 25'),
    ('CarbrasMar', 'CarbrasMar 26'),
    ('CarbrasMar', 'CarbrasMar 30'),
    ('CarbrasMar', 'CarbrasMar 32'),
    ('CarbrasMar', 'CarbrasMar 32.4'),
    ('CarbrasMar', 'CarbrasMar 32.3'),
    ('CarbrasMar', 'CarbrasMar 35'),
    ('CarbrasMar', 'CarbrasMar 36.8'),
    ('CarbrasMar', 'CarbrasMar 37'),
    ('CarbrasMar', 'CarbrasMar 39'),
    ('CarbrasMar', 'CarbrasMar 39.5'),
    ('CarbrasMar', 'CarbrasMar 41'),
    ('CarbrasMar', 'CarbrasMar 44'),
    ('CarbrasMar', 'CarbrasMar 46'),
    ('CarbrasMar', 'CarbrasMar 48'),
    ('CarbrasMar', 'CarbrasMar 50'),
    ('CarbrasMar', 'Carbrasmar 55'),
    ('CarbrasMar', 'CarbrasMar 58'),
    ('CarbrasMar', 'CarbrasMar 61'),
    ('CarbrasMar', 'CarbrasMar 74'),
    ('CarbrasMar', 'CarbrasMar 109'),
    ('Catamarã', 'Catamarã 26'),
    ('Celebrity', 'Celebrity 220'),
    ('Celebrity', 'Celebrity 220'),
    ('Chaparral', 'Chaparral'),
    ('Chaparral', 'Chaparral 27'),
    ('Chris Craft', 'Chris Craft 30 Crowne'),
    ('Chris Craft', 'Chris Craft 33'),
    ('Cimitarra', 'Cimitarra 27'),
    ('Cimitarra', 'Cimitarra 270'),
    ('Cimitarra', 'Cimitarra 270 Plus'),
    ('Cimitarra', 'Cimitarra 290'),
    ('Cimitarra', 'Cimitarra 340'),
    ('Cimitarra', 'Cimitarra 38 HT'),
    ('Cimitarra', 'Cimitarra 410'),
    ('Cimitarra', 'Cimitarra 44'),
    ('Cimitarra', 'Cimitarra'),
    ('Cimitarra', 'Cimittarra'),
    ('Cimitarra 46', 'Cimitarra 46'),
    ('Cobra', 'Cobra Marbella 22'),
    ('Cobra', 'Marbella 22'),
    ('Cobra', 'Cayman 23'),
    ('Cobra', 'Cobra 27'),
    ('Cobra', 'Cobra Link 27'),
    ('Cobra', 'Cobra 30 Infinity'),
    ('Cobra', 'Cobra 30 Infinity'),
    ('Cobra', 'Cobra Infinity 30'),
    ('Cobra', 'Cobra 32 Capri Open'),
    ('Cobra', 'Cobra 32 Monte Carlo'),
    ('Cobra', 'Cobra Capri 32'),
    ('Cobra', 'Cobra Capri 32'),
    ('Cobra', 'Cobra Capri 32 Fly'),
    ('Cobra', 'Cobra Capri Open 32'),
    ('Cobra', 'Cobra Montecarlo 32'),
    ('Cobra', 'Cobra Portofino 36'),
    ('Cobra', 'Cobra Ibiza 40'),
    ('Cobra', 'Cobra Ibiza 40 Plus'),
    ('Colunna', 'Colunna Sport 32'),
    ('Conam', 'Conam 58 Sport'),
    ('Coral', 'coral 22'),
    ('Coral', 'coral 220'),
    ('Coral', 'coral 290'),
    ('Coral', 'Coral 300'),
    ('Coral', 'Coral 31'),
    ('Coral', 'Angra 32'),
    ('Coral', 'Coral 32'),
    ('Coral', 'Coral 34'),
    ('Coral', 'Coral 41'),
    ('Cranchi', 'Cranchi 31'),
    ('Cranchi', 'Cranchi 31 Aquamarina'),
    ('Cranchi', 'Cranchi 33 Endurance'),
    ('Cranchi', 'Cranchi 34 Zaffiro'),
    ('Cranchi', 'Cranchi 35'),
    ('Cranchi', 'Cranchi 36 Esmeraldo'),
    ('Cranchi', 'Cranchi 37 Smeraldo'),
    ('Cranchi', 'Cranchi 39 Endurance'),
    ('Cranchi', 'Cranchi 40 Mediterranée'),
    ('Cranchi', 'Cranchi 40 Smeraldo'),
    ('Cranchi', 'Cranchi 41 Endurance'),
    ('Cranchi', 'Cranchi 43 HT Mediterranée'),
    ('Cranchi', 'Cranchi Atlantique 48'),
    ('Cranchi', 'Cranchi 50'),
    ('D Leon', 'Trawler 72'),
    ('Diamar', 'Bullet 39'),
    ('DM', 'DM 26'),
    ('DM', 'DM 38'),
    ('DM', 'DM 41'),
    ('DM', 'DM 42'),
    ('DM', 'DM 54'),
    ('Dolphin Catamarans', 'Trawler 40'),
    ('Dolphin Catamarans', 'Catamaran 70 Trawler'),
    ('Dumar', 'Wellcraft'),
    ('Ecomariner', 'Ecomariner 25'),
    ('Ecomariner', 'Alfa 300'),
    ('Ecomariner', 'Cigarette 360'),
    ('Ecomariner', 'Cigarrete 36'),
    ('Ecomariner', 'White Spirit 38'),
    ('Ecomariner', 'Ecomariner Open 39'),
    ('Ecomariner', 'Ecomariner Offshore 42'),
    ('Ecomariner', 'Ecomariner 44'),
    ('Ecomariner', 'Ecomariner Discovery 440'),
    ('Ecomariner', 'Ecomariner 45'),
    ('Ecomariner', 'Ecomariner 55'),
    ('Engemare', 'Engemare 48'),
    ('Engemare', 'Engemare 52'),
    ('Escuna', 'Escuna 60'),
    ('Escuna', 'Escuna 76'),
    ('Evolution', 'Evolution 225'),
    ('Evolution', 'Evolution 225 Cabinada'),
    ('Evolution', 'Evolution 255'),
    ('Evolution', 'Evolution 265'),
    ('Evolution', 'Evolution 265 Cab'),
    ('Evolution', 'Evolution 265 Open'),
    ('Evolution', 'Evolution 265 Platinum'),
    ('Evolution', 'Evolution 310'),
    ('Evolution', 'Evolution 335'),
    ('Evolve', 'Evolve 225 Cab'),
    ('Excel', 'Excel 82'),
    ('Fairline', 'Fairline Targa 29'),
    ('Fairline', 'Fairline Targa 34'),
    ('Fairline', 'Fairline Targa 37'),
    ('Fairline', 'Fairline 38 Fly'),
    ('Fairline', 'Fairline Phantom 40'),
    ('Fairline', 'Fairline Squadron 42'),
    ('Fairline', 'Fairline 43'),
    ('Fairline', 'Fairline 52'),
    ('Fairline', 'Fairline Squadron 55'),
    ('Fairline', 'Fairline 80'),
    ('Fast', 'Catamaran 29.5'),
    ('Fast', 'Senna Fast'),
    ('Ferretti', 'Ferretti 38'),
    ('Ferretti', 'Ferretti 40'),
    ('Ferretti', 'Ferretti 43'),
    ('Ferretti', 'Ferretti 46'),
    ('Ferretti', 'Ferretti 46 Platinum'),
    ('Ferretti', 'Ferretti Spirit Platinum 46'),
    ('Ferretti', 'Platinum 46'),
    ('Ferretti', 'Spirit Platinum 46'),
    ('Ferretti', 'Ferretti 48 OffShore'),
    ('Ferretti', 'Ferretti 50'),
    ('Ferretti', 'Pershing 52'),
    ('Ferretti', 'Ferretti 53'),
    ('Ferretti', 'Ferretti 55'),
    ('Ferretti', 'Ferretti 58'),
    ('Ferretti', 'Ferretti 60'),
    ('Ferretti', 'Ferretti 65'),
    ('Ferretti', 'Ferretti 68'),
    ('Ferretti', 'Ferretti 70'),
    ('Ferretti', 'Ferretti 700'),
    ('Ferretti', 'Ferretti 74'),
    ('Ferretti', 'Ferretti 760'),
    ('Ferretti', 'Ferretti 78'),
    ('Ferretti', 'Ferretti 80'),
    ('Ferretti', 'Ferretti 81'),
    ('Ferretti', 'Ferretti 830'),
    ('Ferretti', 'Ferretti'),
    ('Ferretti', 'Ferretto'),
    ('Fibrafort', 'Focker 190 Extreme'),
    ('Fibrafort', 'Focker 215'),
    ('Fibrafort', 'Fisherman 23.8'),
    ('Fibrafort', 'Focker 240'),
    ('Fibrafort', 'Focker 255'),
    ('Fibrafort', 'Focker 280'),
    ('Fighter', 'UB 22'),
    ('Fighter', 'Fighter 26'),
    ('Fighter', 'Fighter 32'),
    ('Fighter', 'UB 32'),
    ('Fighter', 'Fighter 33'),
    ('Fighter', 'Fighter 38'),
    ('Fishing', 'Fishing 22'),
    ('Fishing', 'Fishing 25'),
    ('Fishing', 'Fishing 26'),
    ('Fishing', 'Fishing 26 Hobby Cat'),
    ('Fishing', 'Fishing 265'),
    ('Fishing', 'Fishing 28 WA'),
    ('Fishing', 'Fishing 32'),
    ('Fishing', 'Fishing 32 St Tropez'),
    ('Fishing', 'Fishing 32 WA'),
    ('Fishing', 'Fishing 330 Raptor'),
    ('Fishing', 'Fishing 38'),
    ('Fishing', 'Fishing 38 Hobby Cat'),
    ('Florida Marine', '270 Ocean'),
    ('Florida Marine', 'Ocean 33'),
    ('Focker', 'Focker 222'),
    ('Focker', 'Focker 23'),
    ('Focker', 'Focker 24'),
    ('Focker', 'Focker 255'),
    ('Focker', 'Focker 270'),
    ('Focker', 'Focker 280'),
    ('Focker', 'Focker 280 GT'),
    ('Focker', 'Focker 305'),
    ('Focker', 'Focker 310 GT'),
    ('Focker', 'Focker 330'),
    ('Focker', 'Focker 377'),
    ('Focker', 'Focker 400'),
    ('Focker', 'Focker 420'),
    ('Forza', 'Forza 44'),
    ('FS', 'FS200'),
    ('FS', 'FS230'),
    ('FS', 'FS230 SIRENA'),
    ('FS', 'Fs 350'),
    ('Futura', 'Futura 28 Sport Cabinada'),
    ('Futura', 'Futura Express 32'),
    ('Genesis', 'Genesis 40 SHT'),
    ('Goumet', 'Goumet 53'),
    ('Hanseatica', 'Hanseatica 85'),
    ('HD', 'HD 7.0'),
    ('HD', 'HD STARK 7.0'),
    ('HD', 'HD 7.9 Cuddy'),
    ('HD', 'HD Saga 29'),
    ('Inace', 'Trawler 68'),
    ('Intermarine', 'Golden Yachts'),
    ('Intermarine', 'Intermarine Oceanic 26'),
    ('Intermarine', 'Intermarine Oceanic 32'),
    ('Intermarine', 'Intermarine Oceanic 32 Plus'),
    ('Intermarine', 'Intermarine Panther 33'),
    ('Intermarine', 'Cigarrette 36'),
    ('Intermarine', 'Intermarine Cigarette 36'),
    ('Intermarine', 'Intermarine Oceanic 36'),
    ('Intermarine', 'Intermarine 380 Full'),
    ('Intermarine', 'Intermarine Scarab 38'),
    ('Intermarine', 'Intermarine Sunfish 385'),
    ('Intermarine', 'Intermarine Excalibur 39'),
    ('Intermarine', 'Intermarine 400 Full'),
    ('Intermarine', 'Intermarine Oceanic 40'),
    ('Intermarine', 'Intermarine Scarab 41'),
    ('Intermarine', 'Intermarine Cougar 42'),
    ('Intermarine', 'Intermarine 430 Full'),
    ('Intermarine', 'Intermarine 440 Full'),
    ('Intermarine', 'Intermarine 440 Full Gold'),
    ('Intermarine', 'Intermarine Oceanic 44'),
    ('Intermarine', 'Intermarine Excalibur 45'),
    ('Intermarine', 'Intermarine 46 OffShore'),
    ('Intermarine', 'Intermarine 460 Full'),
    ('Intermarine', 'Intermarine OffShore 46'),
    ('Intermarine', 'Intermarine 480 Full'),
    ('Intermarine', 'Intermarine 48S'),
    ('Intermarine', 'Atlantis 500'),
    ('Intermarine', 'Intermarine 500 Full'),
    ('Intermarine', 'Intermarine Atlantis 500'),
    ('Intermarine', 'Intermarine 520 Full'),
    ('Intermarine', 'Intermarine 53'),
    ('Intermarine', 'Intermarine 55 OffShore'),
    ('Intermarine', 'Intermarine 560 Full'),
    ('Intermarine', 'Intermarine 580 Full'),
    ('Intermarine', 'Intermarine 600 Full'),
    ('Intermarine', 'Intermarine Azimut 600'),
    ('Intermarine', 'Intermarine 680 Full'),
    ('Intermarine', 'Intermarine 68S'),
    ('Intermarine', 'Intermarine 740 Full'),
    ('Intermarine', 'Intermarine 75'),
    ('Intermarine', 'Intermarine 760 Full'),
    ('Jeanneau', 'NC 11'),
    ('Lenzi', 'Thorus 275'),
    ('Lenzi', 'Thorus 405'),
    ('Lenzi&amp;kastigar', 'Thorus 305'),
    ('Logic', 'Logic 33'),
    ('Maggiore', 'Maggiore 48 Fly'),
    ('Magna', 'Magna 21'),
    ('Magna', 'Magna 26'),
    ('Magna', 'Magna 27.5'),
    ('Magna', 'Magna 27.8'),
    ('Magna', 'Magna 29'),
    ('Magna', 'Magna 30.5'),
    ('Magna', 'Magna 32.3'),
    ('Magna', 'Magna 386'),
    ('Magnum', 'Magnum 28'),
    ('Magnum', 'Magnum 29'),
    ('Magnum', 'Magnum 39'),
    ('Magnum', 'Magnum 39 Plus'),
    ('Maiora', 'Maiora DP 100'),
    ('Mara', 'Mara 24'),
    ('Marbono', 'Marbono 42'),
    ('Mares', 'Mares 30'),
    ('Mares', 'Mares 35'),
    ('Mares', 'Mares 40'),
    ('Mares', 'Mares 45'),
    ('Mares', 'Mares 50'),
    ('Mares', 'Mares Cat 64'),
    ('Marka', 'Marka 26'),
    ('Martinelli', 'Malrbono'),
    ('Maxima Yachts', '38 ht'),
    ('MCP', 'Trawler 98'),
    ('Millenium', 'Milenium 240'),
    ('Monterey', '194FS'),
    ('NHD', 'NHD 370'),
    ('Overmarine Grupe Rodriguez', 'Mangusta 92 Open'),
    ('Palmer Johnson', 'Palmer Johnson 120'),
    ('Perimar', 'Perimar 27'),
    ('Perimar', 'Perimar 34'),
    ('Perimar', 'Perimar 38'),
    ('Perimar', 'Perimar 400'),
    ('Pershing', 'Pershing 43'),
    ('Pershing', 'Pershing 55'),
    ('Phantom', 'Phantom 360'),
    ('Phantom', 'Phantom 510 HT'),
    ('Phantom', 'Phantom 62'),
    ('Phoenix', 'Phoenix 23'),
    ('Phoenix', 'Phoenix 290'),
    ('Phoenix', 'Phoenix 360 Full'),
    ('Planet Boat', 'Caprice 54'),
    ('PRESTIGE', 'PRESTIGE 400 FLY'),
    ('PRESTIGE', 'PRESTIGE 440S HT'),
    ('PRESTIGE', 'Prestige 450'),
    ('PRESTIGE', 'PRESTIGE 500 FLY'),
    ('PRESTIGE', 'Prestige 550'),
    ('PRESTIGE', 'Prestige 620 fly'),
    ('Preveza', 'Preveza 50'),
    ('Preveza', 'Preveza 58'),
    ('Princes', 'Princess V42'),
    ('Princess', 'Princess 42 Fly'),
    ('Princess', 'Princess V45'),
    ('Princess', 'Princess V52'),
    ('Princess', 'Princess 56 Fly'),
    ('Princess', 'Princess V 58'),
    ('Princess', 'Princess P64'),
    ('Princess', 'Princess 80'),
    ('Pró Boats', 'Pró Fish 250'),
    ('Quantum', 'Quantum-Mar 33'),
    ('Quantum', 'Quantum-Mar 39'),
    ('Real', '41 Top'),
    ('Real', 'Real Summer 20'),
    ('Real', 'Real 22'),
    ('Real', 'Real Eagle 22'),
    ('Real', 'Real 24'),
    ('Real', 'Real 24 Class'),
    ('Real', 'Real 24 Class'),
    ('Real', 'Real'),
    ('Real', 'Real 25 Profish UB'),
    ('Real', 'Real 25 Summer'),
    ('Real', 'Real 26'),
    ('Real', 'Real 26'),
    ('Real', 'Real 26 Class'),
    ('Real', 'Real 26 Racerpro'),
    ('Real', 'Real Class 26 Open'),
    ('Real', 'Real 28'),
    ('Real', 'Real 29'),
    ('Real', 'Real Class 29'),
    ('Real', 'Real 300 Sport'),
    ('Real', 'Real 31'),
    ('Real', 'Real 315'),
    ('Real', 'Real 315'),
    ('Real', 'Real 32'),
    ('Real', 'Real 34 + 4'),
    ('Real', 'Real Top 350'),
    ('Real', 'Real 36 Extasy'),
    ('Real', 'Real 36,5'),
    ('Real', 'Real 38'),
    ('Real', 'Real 38 Class'),
    ('Real', 'Real Top 38'),
    ('Real', 'Real 40 Fly'),
    ('Real', 'Real Top 40'),
    ('Real', 'Real 41'),
    ('Real', 'Real 41 Ht'),
    ('Real', 'Real 41.5 Top'),
    ('Real', 'Real top 41'),
    ('Real', 'Real 45'),
    ('Real', 'Real 46'),
    ('Real Powerboats', 'Real 310'),
    ('Real Powerboats', 'Real 34'),
    ('Regal', 'Regal 19'),
    ('Regal', 'Regal 21'),
    ('Regal', 'Regal 23 Ventura'),
    ('Regal', 'Regal 242'),
    ('Regal', 'Regal 25'),
    ('Regal', 'Regal 25.50'),
    ('Regal', 'Regal 25.80'),
    ('Regal', 'Regal 26.6'),
    ('Regal', 'Regal Commodore 27.60'),
    ('Regal', 'Regal 28'),
    ('Regal', 'Regal 28.5'),
    ('Regal', 'Regal 29.2'),
    ('Regal', 'Regal 310'),
    ('Regal', 'Regal 32.2'),
    ('Regal', 'Regal 32.2 Comodore'),
    ('Regal', 'Regal 32.6'),
    ('Regal', 'Regal 40 Fly'),
    ('REGGAL', 'REGGAL 2520'),
    ('Rio Star', 'Rio Star Open 23'),
    ('Rio Star', 'Rio Star 28'),
    ('Rio Star', 'Rio Star UB 28'),
    ('Rio Star', 'Rio Star 37'),
    ('Rio Star', 'Rio Star 40'),
    ('Rio Star', 'Rio Star 42'),
    ('Rio Star', 'Rio Star 47'),
    ('Rio Star', 'Riostar 51'),
    ('Rio Star', 'Rio Star 55 OffShore'),
    ('Rio Star', 'Rio Star Pollux 55'),
    ('Rio Star', 'Rio Star SportFish'),
    ('Rio Star', 'Trawler 82'),
    ('Rival', 'Rival 36'),
    ('Runner', 'Runner 260'),
    ('Runner', 'Runner Eclipse 26'),
    ('Runner', 'Runner 290'),
    ('Runner', 'Runner 330'),
    ('Runner', 'Runner 330'),
    ('Runner', 'Runner 335'),
    ('Runner', 'Runner 380'),
    ('Runner', 'Runner 405'),
    ('Runner', 'Runner 410'),
    ('Runner', 'Runner 460'),
    ('Runner', 'Runner 470'),
    ('Runner', 'Runner 480'),
    ('Runner', 'Runner 520'),
    ('Santana', 'Santana 40'),
    ('Santana', 'Santana 40'),
    ('Schaefer', 'Phantom 640'),
    ('Schaefer', 'Phantom 303'),
    ('Schaefer', 'Phantom'),
    ('Schaefer', 'Phantom'),
    ('Schaefer', 'Phantom 62'),
    ('Schaefer', 'Phantom'),
    ('Schaefer Yachts', 'Phantom 235'),
    ('Schaefer Yachts', 'Phantom 240'),
    ('Schaefer Yachts', 'Phantom 260'),
    ('Schaefer Yachts', 'Phantom 290'),
    ('Schaefer Yachts', 'Phantom 300'),
    ('Schaefer Yachts', 'Phantom 300 Sport'),
    ('Schaefer Yachts', 'Phantom 345'),
    ('Schaefer Yachts', 'Phantom 36.5'),
    ('Schaefer Yachts', 'Phantom 360'),
    ('Schaefer Yachts', 'Phantom 375'),
    ('Schaefer Yachts', 'Phantom 37.5 Fly'),
    ('Schaefer Yachts', 'Phantom 385'),
    ('Schaefer Yachts', 'Phantom 400'),
    ('Schaefer Yachts', 'Phantom 400 FLY'),
    ('Schaefer Yachts', 'Phantom 470'),
    ('Schaefer Yachts', 'Phantom 480'),
    ('Schaefer Yachts', 'Phantom 500 Fly'),
    ('Schaefer Yachts', 'Phantom 500 HT'),
    ('Schaefer Yachts', 'Phantom 510 Fly'),
    ('Schaefer Yahcts ', 'Phantom 80'),
    ('Sea Baron', 'Sea Baron 34'),
    ('Sea Crest', 'Sea Crest 24.5'),
    ('Sea Ray', 'Sea Ray 190 Sport Boat'),
    ('Sea Ray', 'Sea Ray 205 Sport Boat'),
    ('Sea Ray', 'Sea Ray 230 SLX'),
    ('Sea Ray', 'Sea Ray 230 Sundancer'),
    ('Sea Ray', 'Sea Ray 260 Sundancer'),
    ('Sea Ray', 'Sea Ray 280 Sundancer'),
    ('Sea Ray', 'Sea Ray 280 Sundancer'),
    ('Sea Ray', 'Sea Ray 280 Sundeck'),
    ('Sea Ray', 'Sea Ray 310 Sundancer'),
    ('Sea Ray', 'Sea Ray Amberjack 315'),
    ('Sea Ray', 'Sea Ray 335 Sundancer'),
    ('Sea Ray', 'Sea Ray 350 Sundancer'),
    ('Sea Ray', 'Sea Ray 350 Sundancer'),
    ('Sea Ray', 'Sea Ray 35.5'),
    ('Sea Ray', 'Sea Ray 36.5'),
    ('Sea Ray', 'Sea Ray 36.5 Sundancer'),
    ('Sea Ray', 'Sea Ray 370 Sundancer'),
    ('Sea Ray', 'Sea Ray 375'),
    ('Sea Ray', 'Sea Ray 39.5'),
    ('Sea Ray', 'Sea Ray 44 Sundancer'),
    ('Sea Ray', 'Sea Ray 45.5 Sundancer'),
    ('Sea Ray', 'Sea Ray 460 Sundancer'),
    ('Sea Ray', 'Sea Ray 51.5'),
    ('Sea Star', 'Sea Star 19'),
    ('Sea Wolf', 'Sea Wolf 23'),
    ('seaswirl', 'seaswirl 26'),
    ('Seatack Ind. e Com. Ltda', 'Runner 290'),
    ('Seatack Ind. e Com. Ltda', 'Runner 335'),
    ('Sedna', 'SF 32'),
    ('Sedna', 'Fighter 32'),
    ('Sedna', 'Sedna XF 335'),
    ('Sedna', 'SF 33'),
    ('Sedna', 'SF 38'),
    ('Sedna', 'SF 38 Pesca'),
    ('Sedna', 'Sedna 42 Fly'),
    ('Sedna', 'CarbrasMar 50'),
    ('Sedna', 'SF 50'),
    ('Sedna', 'SEDNA 54'),
    ('Segue', 'Segue 32 Open'),
    ('Segue', 'Segue 40 Custon'),
    ('Segue', '45 Ht'),
    ('Segue', 'Segue 45 Ht'),
    ('Segue', 'Segue 48'),
    ('Segue', 'Segue 55 Fly'),
    ('Segue', 'Segue 58 HT'),
    ('Segue', 'Segue 58 HT Mini Fly'),
    ('Segue', 'Segue 60'),
    ('Segue', 'Segue 72'),
    ('Senna', 'Jet Boat Colluna'),
    ('Sessa Marine', 'Sessa C36'),
    ('Sessa Marine', 'Sessa C38'),
    ('Sessa Marine', 'Sessa C40'),
    ('Sessa Marine', 'Sessa F42'),
    ('Sessa Marine', 'Sessa C44'),
    ('Sessa Marine', 'Sessa F48'),
    ('Six Star', 'Six Star 46'),
    ('Solara', 'Solara'),
    ('Solara 52', 'Solara 52'),
    ('Star Boats', 'Revolution 46'),
    ('StarFisher', 'StarFisher 1060'),
    ('Sterlig Yachts', 'Sterlig 41 Trawler'),
    ('Sterling', 'Sterling 28'),
    ('Sunline', 'Sunline 28'),
    ('Sunline', 'Sunline 315'),
    ('Sunseeker', 'Sunseeker Manhattan 53'),
    ('Sunseeker', '74'),
    ('Sunseeker', 'Manhatan 74'),
    ('Super Boats', 'Catamarã'),
    ('Super Boats', 'Catamarã 45'),
    ('Super Boats', 'V 52'),
    ('Tango', 'Tango 44 Fly'),
    ('Tecnema', 'Tecnema 54'),
    ('Tecnema', 'Tecnema 60'),
    ('Tecnema', 'Tecnema 65'),
    ('Tecnema', 'Tecnema 67'),
    ('Tecnema', 'Tecnema 98'),
    ('Tecnoboat', 'Tecnoboat Express 32'),
    ('TecnoBoats', 'Futura 8.0'),
    ('TecnoBoats', 'Futura 8.0'),
    ('TecnoBoats', 'Futura 28'),
    ('Tecnomarine', 'Futura 28 Sport Fishing'),
    ('Tecnomarine', 'Tecnomarine 31'),
    ('Tecnomarine', 'Tecnomarine 31 OffShore'),
    ('Tecnomarine', 'Altura'),
    ('Tecnomarine', 'Altura 40 Fly'),
    ('Tecnomarine', 'Tecnomarine 41 Offshore'),
    ('Tecnomarine', 'Tecnomarine 42 OffShore'),
    ('Tecnomarine', 'Tecnomarine 43'),
    ('Tecnomarine', 'Tecnomarine 53 Fly'),
    ('Tecnomarine', 'Tecnomarine 53 OffShore'),
    ('Tecnomarine', 'Tecnomarine 61'),
    ('Thop Boats', 'Thop Cat Fishing 3.0'),
    ('Thop Boats', 'Thop Cat Fishing 26'),
    ('Thop Cat', 'Thop Cat Fishing 3.0'),
    ('Top Gun', 'Top Gun 38 TS'),
    ('TOP LINE', 'TOP LINE 410'),
    ('TOP LINE 410', 'Galapagos'),
     ('Trawler', 'Trawler 40'),
    ('Trawler', 'Trawler 46'),
    ('Trawler', 'Trawler 50'),
    ('Trawler', 'Trawler 54'),
    ('Trawler', 'Trawler 60'),
    ('Trawler', 'Trawler 68'),
    ('Triton', 'Triton 200'),
    ('Triton', 'Triton 240'),
    ('Triton', 'Triton 260'),
    ('Triton', 'Triton i275'),
    ('Triton', 'Triton 280'),
    ('Ventura', 'Ventura 195'),
    ('Ventura', 'Ventura 20'),
    ('Ventura', 'Ventura 23'),
    ('Ventura', 'Ventura 26'),
    ('Ventura', 'Ventura 265 Confort'),
    ('Yacxo', 'Yacxo 337'),
    ('Yacxo 357', 'Yacxo 357');

-- motor
INSERT INTO motor_cadastrado (marca, modelo)
VALUES
    ('Caterpilla', 'Caterpilla Caterpilla - 1622HP - Diesel'),
    ('Caterpillar', 'Caterpillar - - 1653HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3106 - 350HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3116 - 350HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3126 - 420HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3208 - 435HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3408 - 585HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3408 - 800HP - Diesel'),
    ('Caterpillar', 'Caterpillar 3412 - 1200HP - Diesel'),
    ('Caterpillar', 'Caterpillar 420 - 420HP - Diesel'),
    ('Caterpillar', 'Caterpillar 435 - 435HP - Diesel'),
    ('Caterpillar', 'Caterpillar 700 - 700HP - Diesel'),
    ('Caterpillar', 'Caterpillar 750 - 750HP - Diesel'),
    ('Caterpillar', 'Caterpillar C32 - 1675HP - Diesel'),
    ('Caterpillar', 'Caterpillar C32 ACERT V12 - 1825HP - Diesel'),
    ('Cummins', 'Cummins 150 - 150HP - Diesel'),
    ('Cummins', 'Cummins 480 - 480HP - Diesel'),
    ('Cummins', 'CUMMINS 5,9L - 425HP - Diesel'),
    ('Cummins', 'Cummins 500 - 500HP - Diesel'),
    ('Cummins', 'Cummins 600 - 600HP - Diesel'),
    ('Cummins', 'Cummins 6CT - 220HP - Diesel'),
    ('Cummins', 'cummins Axus 350 - 350HP - Diesel'),
    ('Cummins', 'Cummins CMD ZEUS 380 - 364HP - Diesel'),
    ('Cummins', 'Cummins Cummins - 400HP - Diesel'),
    ('Cummins', 'Cummins Cummins 350 - 350HP - Diesel'),
    ('Cummins', 'CUMMINS Cummins QSB 5,9 380 CV - 380HP - Diesel'),
    ('Cummins', 'CUMMINS Cummins QSB 8,3 600 CV - 600HP - Diesel'),
    ('Cummins', 'Cummins Cummins QSD 2.0L - 170HP - Diesel'),
    ('Cummins', 'Cummins NTA 855 - 500HP - Diesel'),
    ('Cummins', 'Cummins NTA 855 M3 - 420HP - Diesel'),
    ('Cummins', 'Cummins QSB - 435HP - Diesel'),
    ('Cummins', 'Cummins QSB 5.9 - 355HP - Diesel'),
    ('Cummins', 'Cummins QSD 4.2L - 270HP - Diesel'),
    ('Detroit', 'Detroit 8VF92 - 735HP - Diesel'),
    ('Evinrude', 'Evinrude 175 Ficht - 175HP - Gasolina'),
    ('Evinrude', 'Evinrude 220 - 220HP - Gasolina'),
    ('Evinrude', 'Evinrude E-tec - 115HP - Gasolina'),
    ('Evinrude', 'Evinrude E-Tec - 150HP - Gasolina'),
    ('Evinrude', 'Evinrude E-Tec - 225HP - Gasolina'),
    ('Evinrude', 'Evinrude E-Tec - 250HP - Gasolina'),
    ('Evinrude', 'Evinrude EFI - 150HP - Gasolina'),
    ('Evinrude', 'Evinrude EFI - 150HP - Gasolina'),
    ('Evinrude', 'Evinrude Ficht Ram - 225HP - Gasolina'),
    ('Evinrude', 'Evinrude Fight Ram - 250HP - Gasolina'),
    ('Evinrude', 'Evinrude Optimax - 200HP - Gasolina'),
    ('Evinrude', 'Evinrude Vindicator - 200HP - Gasolina'),
    ('Ford', 'Ford Cargo - 380HP - Diesel'),
    ('GM', 'GM 900 - 900HP - Diesel'),
    ('Johnson', 'Johnson Johnson - 175HP - Gasolina'),
    ('Johnson', 'Johnson Johnson 250 - 250HP - Gasolina'),
    ('Johnson', 'Johnson Venon - Carburado - 225HP - Gasolina'),
    ('MAN', 'MAN 1050 - 1050HP - Diesel'),
    ('MAN', 'MAN 1200 - 1200HP - Diesel'),
    ('MAN', 'MAN 1248 - 800HP - Diesel'),
    ('MAN', 'MAN 1300 - 1300HP - Diesel'),
    ('MAN', 'MAN 1350 - 1350HP - Diesel'),
    ('MAN', 'MAN 1400 - 1400HP - Diesel'),
    ('MAN', 'MAN 1500 - 1500HP - Diesel'),
    ('MAN', 'MAN 1550 - 1550HP - Diesel'),
    ('MAN', 'MAN 1800 - 1800HP - Diesel'),
    ('MAN', 'MAN 550 - 550HP - Diesel'),
    ('MAN', 'MAN 580 - 800HP - Diesel'),
    ('MAN', 'MAN 588/800 R6 - 800HP - Diesel'),
    ('MAN', 'MAN 630 - 630HP - Diesel'),
    ('MAN', 'MAN 675 - 675HP - Diesel'),
    ('MAN', 'MAN 700 - 700HP - Diesel'),
    ('MAN', 'MAN 730 - 730HP - Diesel'),
    ('MAN', 'MAN 800 - 800HP - Diesel'),
    ('MAN', 'MAN 820 - 820HP - Diesel'),
    ('MAN', 'MAN 900 - 900HP - Diesel'),
    ('MAN', 'MAN D-2848 LE 403 - 800HP - Diesel'),
    ('MAN', 'MAN MAN - 1400HP - Diesel'),
    ('MAN', 'MAN R6 - 800HP - Diesel'),
    ('MAN', 'MAN R6 (588) - 720HP - Diesel'),
    ('MAN', 'MAN V12 - 1850HP - Diesel'),
    ('MAN', 'MAN V12 1360 - 1360HP - Diesel'),
    ('MAN', 'MAN v12 Common rail - 1224HP - Diesel'),
    ('Mecruiser', 'Mecruiser Mercruiser QSD 350 HP - 350HP - Diesel'),
    ('Mecruiser', 'Mecruiser TDI 4.2 - 370HP - Diesel'),
    ('Megatech', 'Megatech 366 - 400HP - Diesel'),
    ('Megatech', 'Megatech MWM - 285HP - Diesel'),
    ('Megatech', 'Megatech Sprinter - 280HP - Diesel'),
    ('Megateck', 'Megateck Megateck 720 - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 352 - 250HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 352 - 260HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 352 - 285HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 352 A - 175HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 270HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 315HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 320HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 360HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 375HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 400HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 366 - 400HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 442 - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 447 - 650HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 447 - 675HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 447 - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 500 Eletrônico - 500HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 720 - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz 800 Eletrônico - 760HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz BM - 250HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz BM 352 - 250HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz BM-250 - 250HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz LA 366MB 320 hp - 320HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megatech - 400HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz megatech 447 - 600HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megatech 447 - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megatech 500 - 500HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megatech Dumon - 720HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megatech om366 - 400HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Megathec - 320HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU - 175HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU - 250HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU - 350HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU - 366HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU 100 - 420HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU 366 - 320HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz MTU 700 - 700HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz OM 352 Turbo - Intercooler - 210HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz OM 366 - 320HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz OM 366 - 350HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz SPRINTER - 260HP - Diesel'),
    ('Mercedes Benz', 'Mercedes Benz Turbinado Interculer - 210HP - Diesel'),
    ('Mercruiser', 'Mercruiser 6.2 MPI - 375HP - Gasolina'),
    ('Mercruiser', 'Mercruiser V8 8.2 - 430HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 1.7 dti - 120HP - Diesel'),
    ('Mercruiser', 'Mercruiser 1.7L - 120HP - Diesel'),
    ('Mercruiser', 'Mercruiser 2.8 L - 200HP - Diesel'),
    ('Mercruiser', 'Mercruiser 2.8L - 165HP - Diesel'),
    ('Mercruiser', 'Mercruiser 2.8L - 175HP - Diesel'),
    ('Mercruiser', 'Mercruiser 250 - 250HP - Diesel'),
    ('Mercruiser', 'Mercruiser 2T XL EFI - 200HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 3.0L - 135HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 310 - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 350 QSD4 Axius Seacore br3x - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 350 QSD4 Axius Seacore BR3X - 350HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2 - 200HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2 - 200HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.2 - 230HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2 - 250HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2 - 250HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.2 D.Tronic - 320HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2 L - 200HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2L D. Tronic - 270HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2L D. Tronic - 279HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2L D.Tronic - 300HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.2L D.Tronic - 300HP - Diesel'),
    ('Mercruiser', 'Mercruiser 4.3 - 230HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.3 6cc - 230HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.3 GI rabeta Bravo 3 - 230HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.3 MPI - 220HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.3 MPI - 242HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 4.3L - 220HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 496 MAG - 375HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.0 - 300HP - Diesel'),
    ('Mercruiser', 'Mercruiser 5.0 B - 260HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.0 MPI - 260HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.0L - 260HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7 - 250HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7 EFI - 270HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7 L - 250HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7 Magnun - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7 MPI MAG 350 - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 5.7L 350 MAG - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6 cc - 200HP - Diesel'),
    ('Mercruiser', 'Mercruiser 6.2 - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2 - 330HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2 - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2 EFI - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2 MPI - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2 MPI - 375HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 6.2L - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 7.3 V8 - 270HP - Diesel'),
    ('Mercruiser', 'Mercruiser 7.4 - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 7.4 V8 - Bravo 3 - 370HP - Gasolina'),
    ('Mercruiser', 'Mercruiser 8.1L Rabeta Bravo III - 375HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Bravo 3 6.2 - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Bravo 3 7.4 V8 - 370HP - Gasolina'),
    ('Mercruiser', 'Mercruiser CM 4.2 BT - 250HP - Diesel'),
    ('Mercruiser', 'Mercruiser Comodore 292 5.7 - 260HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Dtronic 4.2 - 220HP - Diesel'),
    ('Mercruiser', 'Mercruiser Dtronic 4.2 - 220HP - Diesel'),
    ('Mercruiser', 'Mercruiser Mag 350 - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MAG 350 - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MAG 350 MPI - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MAG 350 RB3 - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Mag 377 - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MAG 8.2 BR-3 - 380HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Magnum 350 Rabeta Bravo 1 - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser magnum MPI - 300HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Mercruiser 3.2 - 320HP - Diesel'),
    ('Mercruiser', 'Mercruiser MPFI 6.2 - 385HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MPI 3.0 - 135HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MPI 5.0 - 260HP - Gasolina'),
    ('Mercruiser', 'Mercruiser MX 6.2 - 320HP - Gasolina'),
    ('Mercruiser', 'Mercruiser Popa - 225HP - Gasolina'),
    ('Mercruiser', 'Mercruiser QSD 2.0L - Bravo III - 170HP - Diesel'),
    ('Mercruiser', 'Mercruiser QSD 2.8L - Bravo III - 230HP - Diesel'),
    ('Mercruiser', 'Mercruiser QSD 2.8L - Bravo III - 230HP - Diesel'),
    ('Mercruiser', 'Mercruiser QSD 4.2 - 320HP - Diesel'),
    ('Mercruiser', 'Mercruiser Rabeta Bravo 3 6.2 - 350HP - Gasolina'),
    ('Mercruiser', 'Mercruiser TDI 3.0 - 260HP - Diesel'),
    ('Mercruiser axius com joystick', 'Mercruiser axius com joystick 2.8L - 220HP - Diesel'),
    ('Mercruiser Diesel', 'Mercruiser Diesel Alfa 2.0 L - 150HP - Diesel'),
    ('Mercruiser Diesel', 'Mercruiser Diesel D 2.8 - 165HP - Diesel'),
    ('Mercury', 'Mercury Optimax 250 XS - 250HP - Gasolina'),
    ('Mercury', 'Mercury 135 Optimax - 135HP - Gasolina'),
    ('Mercury', 'Mercury 175 IFI - 175HP - Gasolina'),
    ('Mercury', 'Mercury 2.8 - 200HP - Diesel'),
    ('Mercury', 'Mercury 225 EFI XL - 225HP - Gasolina'),
    ('Mercury', 'Mercury 225 Optimax- 2005 - 225HP - Gasolina'),
    ('Mercury', 'Mercury 240 EFI-V6 - 240HP - Gasolina'),
    ('Mercury', 'Mercury 370 - 370HP - Diesel'),
    ('Mercury', 'Mercury 4 tempos - 115HP - Gasolina'),
    ('Mercury', 'Mercury 4.2 - 250HP - Diesel'),
    ('Mercury', 'Mercury 4.2 Horse power - 320HP - Diesel'),
    ('Mercury', 'Mercury 4.2l d tronic - 300HP - Diesel'),
    ('Mercury', 'Mercury 6.2 MPI - 350HP - Gasolina'),
    ('Mercury', 'Mercury dlt - 270HP - Diesel'),
    ('Mercury', 'Mercury Dtronic 4.2 - 320HP - Diesel'),
    ('Mercury', 'Mercury EFI - 115HP - Gasolina'),
    ('Mercury', 'MERCURY EFI - 150HP - Gasolina'),
    ('Mercury', 'Mercury EFI - 200HP - Gasolina'),
    ('Mercury', 'Mercury EFI - 200HP - Gasolina'),
    ('Mercury', 'Mercury EFI - 250HP - Gasolina'),
    ('Mercury', 'Mercury EFI 225 - 225HP - Gasolina'),
    ('Mercury', 'Mercury EFI 3.0 - 225HP - Gasolina'),
    ('Mercury', 'Mercury hpi - 250HP - Diesel'),
    ('Mercury', 'Mercury Mag - 370HP - Gasolina'),
    ('Mercury', 'Mercury Mercruiser TDI 4.2 - 370HP - Diesel'),
    ('Mercury', 'Mercury Mercruiser TDI 4.2 370HP - 370HP - Diesel'),
    ('Mercury', 'Mercury mercury 350 - 350HP - Diesel'),
    ('Mercury', 'Mercury Mercury QSB - 220HP - Diesel'),
    ('Mercury', 'Mercury MPI 6.2 - 320HP - Gasolina'),
    ('Mercury', 'Mercury Optimax - 90HP - Gasolina'),
    ('Mercury', 'Mercury Optimax - 200HP - Gasolina'),
    ('Mercury', 'Mercury Optimax - 225HP - Gasolina'),
    ('Mercury', 'Mercury OPTIMAX 150 - 150HP - Gasolina'),
    ('Mercury', 'Mercury Optmax - 115HP - Gasolina'),
    ('Mercury', 'Mercury Popa - 225HP - Gasolina'),
    ('Mercury', 'Mercury QSD - 270HP - Diesel'),
    ('Mercury', 'Mercury Racing - 520HP - Gasolina'),
    ('Mercury', 'Mercury Verado - 200HP - Gasolina'),
    ('Mercury', 'Mercury Verado - 250HP - Gasolina'),
    ('Mercury', 'Mercury Verado - 275HP - Gasolina'),
    ('Mercury', 'Mercury Verado - FourStrock - 300HP - Gasolina'),
    ('Mercury', 'Mercury Verado - popa - 300HP - Gasolina'),
    ('Mercury', 'Mercury Verado 250 - 250HP - Gasolina'),
    ('Mercury', 'Mercury Verado T - 175HP - Gasolina'),
    ('Mercury QSB 220 diesel', 'Mercury QSB 220 diesel Mercury QSB - 220HP - Diesel'),
    ('MTU', 'MTU 1200 - 1200HP - Diesel'),
    ('MTU', 'MTU 12V 183 -TE 94 - 1360HP - Diesel'),
    ('MTU', 'MTU 16V 1300 - 900HP - Diesel'),
    ('MTU', 'MTU 1820 - 1820HP - Diesel'),
    ('MTU', 'MTU 366 - 320HP - Diesel'),
    ('MTU', 'MTU Heavy Duty - 220HP - Diesel'),
    ('MTU', 'MTU Mondrive 1150 - 1150HP - Diesel'),
    ('MTU', 'MTU MTU - 700HP - Diesel'),
    ('MTU', 'MTU MTU - 767HP - Diesel'),
    ('MTU', 'MTU MTU - 914HP - Diesel'),
    ('MTU', 'MTU MTU 1200 - 1200HP - Diesel'),
    ('MTU', 'MTU MTU 12V - 2000HP - Diesel'),
    ('MTU', 'MTU MTU 12V 2000 M92 - 2200HP - Diesel'),
    ('MTU', 'MTU MTU 1300 - 1300HP - Diesel'),
    ('MTU', 'MTU MTU 1500 - 1500HP - Diesel'),
    ('MTU', 'MTU MTU 370 - 370HP - Diesel'),
    ('MWM','MWM 175 - 175HP - Diesel'),
    ('MWM','MWM 250 - 250HP - Diesel'),
    ('MWM','MWM 260 - 260HP - Diesel'),
    ('MWM','MWM 6 cil - 170HP - Diesel'),
    ('MWM','MWM 6cc - 250HP - Diesel'),
    ('MWM','MWM BJ Marine - 260HP - Diesel'),
    ('MWM','MWM Dumont - 260HP - Diesel'),
    ('MWM','MWM MWM - 250HP - Diesel'),
    ('MWM','MWM MWM 110 - 110HP - Diesel'),
    ('MWM','MWM Sprint - 190HP - Diesel'),
    ('MWM','MWM Sprint - 250HP - Diesel'),
    ('MWM','MWM Sprint 6cc - 300HP - Diesel'),
    ('MWM','MWM sprinter - 200HP - Diesel'),
    ('MWM','MWM VPI - 250HP - Diesel'),
    ('MWM','MWM VPI 229 - 250HP - Diesel'),
    ('Optimax','Optimax 200 - 200HP - Gasolina'),
    ('Perkins','Perkins M275 - 275HP - Diesel'),
    ('Scania','Scania 280 - 280HP - Diesel'),
    ('Scania','Scania 675 - 675HP - Diesel'),
    ('Scania','Scania DI 12 - 675HP - Diesel'),
    ('Scania','Scania DI 1244 - 675HP - Diesel'),
    ('Scania','Scania DS 14 - 475HP - Diesel'),
    ('Scania','Scania DSI 11 - 380HP - Diesel'),
    ('Scania','Scania Dsi 14 - 485HP - Diesel'),
    ('Scania','Scania DSI 14 - 500HP - Diesel'),
    ('Scania','Scania DSI 14 - 585HP - Diesel'),
    ('Scania','Scania Eletronico - 675HP - Diesel'),
    ('Scania','Scania Yanmar - 720HP - Diesel'),
    ('Sprinter','Sprinter MWM - 170HP - Diesel'),
    ('Sprinter','Sprinter MWM210 - 210HP - Diesel'),
    ('Sprinter','Sprinter Sprinter - 250HP - Diesel'),
    ('Volvo','Volvo IPS - 435HP - Diesel'),
    ('Volvo','Volvo IPS - 1200HP - Diesel'),
    ('Volvo Penta','Volvo Penta 3.0 GL - 135HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 300 - 300HP - Diesel'),
    ('Volvo Penta','Volvo Penta 480 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta 5.0 GXI - 275HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.0 GXiE - 270HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.7 - 320HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.7 Gi - 250HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.7 GSI - 270HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.7Gi - 300HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 5.O Gi - 260HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 7.4 - 330HP - Gasolina'),
    ('Volvo Penta','Volvo Penta 7.4 GI - 320HP - Gasolina'),
    ('Volvo Penta','Volvo Penta AD 41 - 200HP - Diesel'),
    ('Volvo Penta','Volvo Penta AQAD 40 - 165HP - Diesel'),
    ('Volvo Penta','Volvo Penta AQAD 41 - 200HP - Diesel'),
    ('Volvo Penta','Volvo Penta D11 - 675HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 575HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 615HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 675HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 700HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 715HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 720HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 - 800HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 800 - 775HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 800 - 800HP - Diesel'),
    ('Volvo Penta','Volvo Penta D12 900 - 900HP - Diesel'),
    ('Volvo Penta','Volvo Penta D13 - 900HP - Diesel'),
    ('Volvo Penta','Volvo Penta D3 - 160HP - Diesel'),
    ('Volvo Penta','Volvo Penta D3 - 190HP - Diesel'),
    ('Volvo Penta','Volvo Penta D3 C/Joystick - 200HP - Diesel'),
    ('Volvo Penta','Volvo Penta D3AD - 220HP - Diesel'),
    ('Volvo Penta','Volvo Penta D4 - 225HP - Diesel'),
    ('Volvo Penta','Volvo Penta D4 - 260HP - Diesel'),
    ('Volvo Penta','Volvo Penta D4 - 300HP - Diesel'),
    ('Volvo Penta','Volvo Penta D4 - 310HP - Diesel'),
    ('Volvo Penta','Volvo Penta D6 - 310HP - Diesel'),
    ('Volvo Penta','Volvo Penta D6 - 350HP - Diesel'),
    ('Volvo Penta','Volvo Penta D6 - 370HP - Diesel'),
    ('Volvo Penta','Volvo Penta D6 - 435HP - Diesel'),
    ('Volvo Penta','Volvo Penta D6 400 - 400HP - Diesel'),
    ('Volvo Penta','Volvo Penta D9 - 500HP - Diesel'),
    ('Volvo Penta','Volvo Penta D9 - 575HP - Diesel'),
    ('Volvo Penta','Volvo Penta GI 8.1 - 375HP - Gasolina'),
    ('Volvo Penta','Volvo Penta GXI - 320HP - Gasolina'),
    ('Volvo Penta','Volvo Penta IPS 350 - 350HP - Diesel'),
    ('Volvo Penta','Volvo Penta IPS 600 C/Joystick - 435HP - Diesel'),
    ('Volvo Penta','Volvo Penta IPS 900 - 700HP - Diesel'),
    ('Volvo Penta','Volvo Penta IPS 950 - 725HP - Diesel'),
    ('Volvo Penta','Volvo Penta IPS-B 500 - 370HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 300 - 296HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 300 - 270HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 300 - 300HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 41 - 200HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 42 - 230HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 42 - 250HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 43 - 190HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 43 - 230HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 44 - 250HP - Diesel'),
    ('Volvo Penta','Volvo Penta KAD 44 - 260HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 63 - 318HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 122 - 615HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 122 P EDC - 610HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 63 - 370HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 63 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 70 - 286HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 73 - 430HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 74 - 430HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 74 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 74 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 74 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta TAMD 75 - 480HP - Diesel'),
    ('Volvo Penta','Volvo Penta V8 - 380HP - Gasolina'),
    ('Volvo Penta','Volvo Penta V8 5.7 - 350HP - Gasolina'),
    ('Volvo Penta','Volvo Penta Volvo Pensa IPS 900 - 700HP - Diesel'),
    ('Volvo Penta', 'Volvo Penta 5.7 GXI Volvo - 320HP - Gasolina'),
    ('Yamaha', 'Yamaha ME 422 - 275HP - Diesel'),
    ('Yamaha', 'Yamaha 2 Tempos - 115HP - Gasolina'),
    ('Yamaha', 'Yamaha 2 tempos - 200HP - Gasolina'),
    ('Yamaha', 'Yamaha 200 - 200HP - Gasolina'),
    ('Yamaha', 'Yamaha 4 Tempos - 225HP - Gasolina'),
    ('Yamaha', 'Yamaha 4Tempos - 300HP - Gasolina'),
    ('Yamaha', 'Yamaha F 150 - 150HP - Gasolina'),
    ('Yamaha', 'Yamaha FOUR STROKE - 300HP - Gasolina'),
    ('Yamaha', 'Yamaha HD 7.0 - 200HP - Gasolina'),
    ('Yamaha', 'Yamaha Hydra Drive - 165HP - Diesel'),
    ('Yamaha', 'Yamaha Hydra Drive - 315HP - Diesel'),
    ('Yamaha', 'Yamaha ME 372 - 165HP - Gasolina'),
    ('Yamaha', 'Yamaha me 422 - 275HP - Diesel'),
    ('Yamaha', 'Yamaha ME 422 - 275HP - Diesel'),
    ('Yamaha', 'Yamaha Yamaha 150 4 Tempos - 150HP - Diesel'),
    ('Yanmar', 'Yanmar 440 - 440HP - Diesel'),
    ('Yanmar', 'Yanmar 6HA2M-DTE M-rating - 405HP - Diesel'),
    ('Yanmar', 'Yanmar 6LPA-STE V-DRIVE - 315HP - Diesel'),
    ('Yanmar', 'Yanmar 6LPA-STZP Bravo 3 - 315HP - Diesel'),
    ('Yanmar', 'Yanmar Yanmar - 435HP - Diesel'),
    ('Yanmar', 'Yanmar Yanmar 720 - 720HP - Diesel'),
    ('Yanmar 4LHA-DTP 200', 'Yanmar 4LHA-DTP 200 Yanmar - 200HP - Diesel');

-- itens
INSERT INTO item_seminovo (item)
VALUES
    ('Adega para vinhos'),
    ('Alfa Laval'),
    ('Alto-falante(s) marinizado'),
    ('Âncora'),
    ('Âncora de popa'),
    ('Ancoragem via GPS (skyhook)'),
    ('Antena de internet'),
    ('Antena de TV (normal)'),
    ('Antena SKY'),
    ('Ar condicionado (máquinas)'),
    ('Ar condicionado de cais'),
    ('Ar condicionado no cockpit (saída)'),
    ('Aspirador de pó central'),
    ('Balsa de sobrevivência'),
    ('Baterias de serviço'),
    ('Bimini'),
    ('Bóia circular'),
    ('Boiler'),
    ('Bomba(s) Água Doce'),
    ('Bomba(s) de porão'),
    ('Bote'),
    ('Bote com motor'),
    ('Bote de borracha'),
    ('Bote rígido (PVC)'),
    ('Bow thruster'),
    ('Bússola'),
    ('Buzina'),
    ('Cabine aberta'),
    ('Cabine de marinheiros'),
    ('Cabine fechada'),
    ('Cabo de Cais'),
    ('Cafeteira'),
    ('Câmera Flir'),
    ('Capa só no fly'),
    ('Capa total'),
    ('Capota estendida na cockpit'),
    ('Capota no fly'),
    ('Carregador de baterias'),
    ('Carreta com pneus'),
    ('Carreta de encalhe'),
    ('Carreta rodencalhe com pneu articulada'),
    ('Carreta rodoviária'),
    ('CD/radio com Bluetooth'),
    ('CFTV (câmeras de segurança)'),
    ('Churrasqueira elétrica na plataforma de popa (Grill)'),
    ('Churrasqueira de carvão'),
    ('Churrasqueira elétrica no cockpit (Grill)'),
    ('Churrasqueira retrátil na popa'),
    ('Comando no fly (segundo)'),
    ('Computador de bordo'),
    ('Contador de corrente'),
    ('Controle remoto de som na popa'),
    ('Controle remoto de som no fly'),
    ('Cooler elétrico'),
    ('Cozinha completa'),
    ('Deck Beach'),
    ('Defensas'),
    ('Dessalinizador'),
    ('Direção hidráulica'),
    ('Ducha de banho na popa'),
    ('DVD'),
    ('Enxoval completo'),
    ('Escada retrátil na plataforma de popa'),
    ('Espaço gourmet na plataforma de popa'),
    ('Espaço gourmet no cockpit'),
    ('Espaço gourmet no fly'),
    ('Estabilizador laterais'),
    ('Estabilizador Seakeeper'),
    ('Exaustores na sala de máquinas (blower)'),
    ('Extintor automático Sea Fire'),
    ('Extintores manuais'),
    ('Farol com controle remoto'),
    ('Fechamento na frente e laterais'),
    ('Fechamento na popa'),
    ('Fechamento no fly'),
    ('Fechamento total'),
    ('Filtro Racor'),
    ('Flap automáticos'),
    ('Flap elétrico Volvo'),
    ('Flaps Hidráulico'),
    ('Fogão a gás'),
    ('Fogão de indução'),
    ('Fogão elétrico'),
    ('Forno elétrico'),
    ('Forno embutido'),
    ('Freezer'),
    ('Frigobar'),
    ('Frigobar de gaveta'),
    ('Geladeira'),
    ('Geladeira grande com freezer'),
    ('Geladeira média'),
    ('Geladeira side by side'),
    ('Gerador'),
    ('GPS'),
    ('Grill elétrico'),
    ('Guarda mancebo em inox'),
    ('Guincho de Âncora elétrico'),
    ('Guincho elétrico para cabos na popa'),
    ('Guincho Hidráulico'),
    ('Hard top de tecido no fly'),
    ('Hard top elétrico'),
    ('Hard top rígido'),
    ('Hard top rígido no fly'),
    ('Holding Tank (águas negras, esgoto)'),
    ('Home-theater'),
    ('Ice maker'),
    ('Inversor de corrente'),
    ('Lancha de apoio com motor'),
    ('Limpador com Desembaçador'),
    ('Louças originais'),
    ('Luz de Fundo (Sub aquática)'),
    ('Luz Strobo'),
    ('Luz Xenon (Sub aquáticas)'),
    ('Manete eletrônico'),
    ('Máquina lava roupas'),
    ('Máquina lava-louças'),
    ('Microondas'),
    ('Mini bar no cockpit'),
    ('Piloto automático'),
    ('Plataforma de popa estendida'),
    ('Plataforma submersível hidráulica'),
    ('Ploter'),
    ('Ponte hidráulica'),
    ('Porta defensas'),
    ('Radar'),
    ('Rádio VHF'),
    ('Salvatagem completa mar aberto'),
    ('Salvatagem completo navegação costeira'),
    ('Sistema de monitoramento'),
    ('Sistema de Posicionamento Ativo'),
    ('Solarium de popa'),
    ('Solarium de proa'),
    ('Som na proa (caixas seladas)'),
    ('Som potente com módulo'),
    ('Sonda'),
    ('Stern thruster'),
    ('Strobo light'),
    ('Subwoofer marinizado'),
    ('Suítes'),
    ('Tampa sala de máquinas com abertura elétrica'),
    ('Tapetes de borracha internos e externos'),
    ('Targa'),
    ('Teka em madeira na plataforma de popa'),
    ('Teka em madeira na popa'),
    ('Teka em madeira no fly'),
    ('Teka em madeira nos passadiços'),
    ('Teka sintética na plataforma de popa'),
    ('Teka sintética no cockpit'),
    ('Teka sintética no fly'),
    ('Teka sintética total'),
    ('Teka total em madeira'),
    ('Terceiro Comando de Popa'),
    ('Toldo'),
    ('Toldo fixo na praça de popa'),
    ('Toldo móvel na praça de popa (elétrico)'),
    ('Toldo móvel na praça de popa (manual)'),
    ('Tomada de cais'),
    ('Turco elétrico no fly'),
    ('Turco na popa'),
    ('TV'),
    ('Ventilador'),
    ('WC Elétrico'),
    ('WC Manual');
    
INSERT INTO item_charter (item, item_lazer)
VALUES
('Cabines ou Cabina', false),
('Banheiros ou Banheiro', false),
('Cozinha completa', false),
('Ar condicionado', false),
('Gerador', false),
('Espaço gourmet', false),
('Churrasqueira a carvão', false),
('Grill elétrico', false),
('Bote de apoio', false),
('Boiler água quente', false),
('Chuveiro na popa', false),
('Plataforma de popa / Plataforma de popa estendida', false),
('Plataforma submersível', false),
('Som ambiente com Bluetooth', true),
('Caixas para bebidas (tipo cooler)', true),
('Macarrão flutuante', true),
('Tapete flutuante', true),
('Caiaque', true);

-- moedas
INSERT INTO moeda(nome, simbolo, codigo_bancario)
VALUES
('Real', 'R$', 'BRL'),
('Dólar', '$', 'USD');

-- user type
INSERT INTO user_type (opcao) VALUES 
('Dono'),
('Administrador'), 
('Editor');

-- cidade 
INSERT INTO cidade (opcao)
VALUES
('Angra dos Reis'),
('Rio de Janeiro');

-- pet friendly
INSERT INTO pet_friendly(opcao)
VALUES
('Não'),
('Pequeno porte'),
('Grande e pequeno porte');

-- tipo passeio
INSERT INTO tipo_passeio(opcao)
VALUES
('Day use'),
('Day use e pernoite'),
('Compartilhado');

-- tripulação skipper
INSERT INTO tripulacao_skipper(opcao)
VALUES
('Tripulação inclusa'),
('Skipper incluso');

-- condições
-- Inserção das condições na tabela condicoes
INSERT INTO condicoes_padrao (opcao)
VALUES
('Os passeios são privativos, não vendemos ingressos.'),
('O tempo é medido desde a hora marcada, mesmo que o cliente atrase no embarque.'),
('Só aceitamos pagamentos no PIX.'),
('Reservas mediante 50% de sinal.'),
('Os 50% restantes devem ser pagos no dia antes do embarque.'),
('Em caso de ressaca impeditiva de navegar, aguardar no dia para remarcação de nova data (chuva, frio, tempo nublado não impedem de navegar).'),
('Toda vida humana conta como passageiro, mesmo no colo.'),
('Caso a Marinha cobre taxa de embarque, fica por conta do cliente.'),
('Desistências só são aceitas com 72 horas de antecedência.'),
('É terminantemente PROIBIDO o uso de drogas.');


-- tipo combustivel
INSERT INTO tipo_combustivel(opcao)
VALUES
('Gasolina'),
('Diesel');

--tipo de propulsao
INSERT INTO
    propulsao (opcao)
VALUES
    ('Zeus'),
    ('IPS'),
    ('Rabeta'),
    ('Pé de galinha eixo direto'),
    ('Pé de galinha V drive'),
    ('Mondrive'),
    ('Motor de popa'),
    ('Turbina a jato');

INSERT INTO app_user (nome, email, user_firebase_id, id_user_type) VALUES 
('Gabriel','jg.7651@gmail.com', 'ls6ZJeBDqfgftdH16ynMTgar7P93', 1);
 INSERT INTO app_user (nome, email, user_firebase_id, id_user_type) VALUES 
('Paulo','paulo2228@gmail.com', 'firebase_id', 2);
 INSERT INTO app_user (nome, email, user_firebase_id, id_user_type) VALUES 
('Alice','alice.almeida@gmail.com', 'firebase_id', 2);

